### ISSUE TITLE
make redis_loader transactional

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/microservices#33]
currently the gff loader (at least) seems to add data from the requested dataset into the db until it hits an error, but there is no rollback of what got added in this case. It seems redis supports a transactional style of loading, which would seem preferable (so as not to have to clean up or start from square one). @alancleary let me know if there are obvious reasons why this is a bad idea, otherwise I might try to work on it now that I'm becoming a redis-loading fool...

**Comment by alancleary** [comment]
@adf-ncgr Yes, Redis supports transactional loading via "[pipelining](https://redis.io/topics/pipelining)". However, I don't think this is the solution here for a couple reasons: 1) this would require significant reworking of the loader code and 2) commands in a pipeline could throw an error (e.g. maybe a key already exists), meaning we would have to figure out how to revert the changes made by the pipeline commands that had already been executed.

Since our databases use the WORM (write once read many) pattern, I think a reasonable solution would be to prevent saving the changes made to the database until the load job completes successfully (we would probably want to use a blocking client for this so another Redis client doesn't unwittingly have its changes deleted if a load fails). The tricky bit here is how we would roll back the changes if a load fails. The naive solution would be to just restart the Redis service, which would load the save made by the last successful load, but this would also take the service (all Redis databases!) offline. I'm not sure what a better solution might be but I'm sure there's something.

**Comment by adf-ncgr** [comment]
@alancleary not sure we're on the same page. from a glance it looks like "pipelining" has to do more with batching queries and/or writes for performance? I was thinking more about: https://redis.io/topics/transactions though admittedly I only glanced at both these pages. I'm not really worried about concurrency between multiple clients, my use case is more like:
a) have loaded a bunch of genomes successfully
b) get to a recalcitrant genome that dies mid-way
c) not wanting to have to go all the way back to a) to try again

it's probably not worth a lot of effort, it just seemed like the sort of thing that could be done easily (at least in the db systems with which I am most familiar- maybe not in redis). anyway, I am explicitly thinking about a mechanism that reverts changes for us when an error is encountered (e.g. using a transaction log); we definitely shouldn't have to write our own!

**Comment by alancleary** [comment]
Ah, I see. Unfortunately, points (1) and (2) are still relevant. Regarding point (2), see the transactions section "[Why Redis does not support roll backs?](https://redis.io/topics/transactions#why-redis-does-not-support-roll-backs)" Basically this means that since the errors we may encounter during a pipeline/transaction are application states, rather than actual Redis errors, there's no way to undo the changes.

**Comment by adf-ncgr** [comment]
Ah, OK; I obviously did not read far enough about transactions. I had vaugely understood that nosql dbs were into ditching support for ACID in favor of BASE, so this makes sense. I'll have to think about whether the application itself could be better at validating the inputs (or maybe just having something else responsible for validation, something that seems to come up a lot)

**Comment by alancleary** [comment]
> it's probably not worth a lot of effort, it just seemed like the sort of thing that could be done easily (at least in the db systems with which I am most familiar- maybe not in redis). anyway, I am explicitly thinking about a mechanism that reverts changes for us when an error is encountered (e.g. using a transaction log); we definitely shouldn't have to write our own!

I think you could achieve the solution I outlined in my first comment pretty easily:

1. Update the loader to return an exit code other than 0 when a load fails
2. Start Redis with a config that only writes to dump.rdb when you explicitly tell it to
3. Write a bash script to load multiple genomes
  a. If the exit code is 0 proceed to the next genome
  b. If the exit code is the load error code, restart the Redis service, which will reset the database to the last time the loader explicitly saved, i.e. right after the last successful load

**Comment by adf-ncgr** [comment]
Ah, OK so the in-memory version would be sort of like the transaction state and the writing to disk would be like the commit? That makes sense. I'm not used to working with databases that reside in memory!

**Comment by adf-ncgr** [comment]
PS. can you point me to some info regarding:
- Start Redis with a config that only writes to dump.rdb when you explicitly tell it to

**Comment by alancleary** [comment]
> Ah, OK; I obviously did not read far enough about transactions. I had vaugely understood that nosql dbs were into ditching support for ACID in favor of BASE, so this makes sense. I'll have to think about whether the application itself could be better at validating the inputs (or maybe just having something else responsible for validation, something that seems to come up a lot)

**Comment by alancleary** [comment]
Whoops! Didn't mean to close the issue; reopening.

> PS. can you point me to some info regarding:
> - Start Redis with a config that only writes to dump.rdb when you explicitly tell it to

You can provide it a config file that disables saving (here's the default config file (search for "save"): https://github.com/redis/redis/blob/3ca6972ecd3e9963f65b9cb1ff050ad60f03563e/redis.conf) or you can set the save value via a command-line flag
```bash
$ redis-server --save ""
```

**Comment by adf-ncgr** [comment]
thanks, I had taken your earlier comment (which I guess was a mistake) to imply RTFM and came to the same conclusion ;)

**Comment by adf-ncgr** [comment]
looking at the loader code now I see there is a no_save option that seems to control whether or not the db gets saved to disk. Doesn't this imply that the dockerized redis instance should already be behaving per "only writes to dump.rdb when you explicitly tell it to"? 

`  def save(self):
    '''Saves the Redis database to disk.'''
    if not self.no_save:
      self.redis_connection.save()`

**Comment by alancleary** [comment]
> looking at the loader code now I see there is a no_save option that seems to control whether or not the db gets saved to disk. Doesn't this imply that the dockerized redis instance should already be behaving per "only writes to dump.rdb when you explicitly tell it to"?
> 
> ` def save(self): '''Saves the Redis database to disk.''' if not self.no_save: self.redis_connection.save()`

Nope. It just controls whether or not the loader explicitly saves when it's done loading; it has no impact on the Redis DB's save configuration.

**Comment by adf-ncgr** [comment]
so if you call it with no_save, the redis server may still have altered what's stored on disk? What's the use case for having such an option?

**Comment by alancleary** [comment]
> so if you call it with no_save, the redis server may still have altered what's stored on disk?

Correct. If Redis is configured to save on its own then your data will eventually persist.

> What's the use case for having such an option?

If you don't want to save your database at all. You would configure Redis not to save at all and use the flag to prevent the loader from forcing Redis to save.

**Comment by adf-ncgr** [comment]
I see. Seems a bit confusing- perhaps it should be the no_save_iff_the_server_has_been_configured_appropriately option. well, I'm learning something anyway, thanks.

**Comment by alancleary** [comment]
> I see. Seems a bit confusing- perhaps it should be the no_save_iff_the_server_has_been_configured_appropriately option. well, I'm learning something anyway, thanks.

Ha! Maybe `--no-explicit-save` plus a more verbose description of the flag would do.

**Comment by adf-ncgr** [comment]
I think this one is effectively addressed by PR #415 so closing

**Comment by alancleary** [comment]
OK. I updated the redis_loader README to document the solution since it's basically a combination of correctly configuring Redis and using the loader correctly.
