### ISSUE TITLE
Gene linkout testing with cicar.ICC4958.gnm2.ann1.Ca_00001 fails

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/microservices#596]
Gene linkout testing with cicar.ICC4958.gnm2.ann1.Ca_00001

- [ ] GCV - no content in GCV layout; POST to https://gcv-microservices.lis.ncgr.org/lis/genes **responds with 500** and payload "500 Internal Server Error Server got itself in trouble" @alancleary 
- [x] LegumeMine
- [ ] Funnotate -- **gene is not present in the tree!** Should be be showing Funnotate link for genes that aren't in trees, @svengato and @adf-ncgr  ??? This results in the "Jump to highlighted feature" link doing nothing, so that's a bug.

Broken linkouts must be fixed before we put this out for LIS review.

Here are the broken linkouts (so you don't have to fire up graphql-server and web-components to reproduce these):

GCV: https://gcv.legumeinfo.org/gene;lis=cicar.ICC4958.gnm2.ann1.Ca_00001

Funnotate: https://funnotate.legumeinfo.org/?gene_name=cicar.ICC4958.gnm2.ann1.Ca_00001

_Originally posted by @sammyjava in https://github.com/legumeinfo/web-components/issues/115#issuecomment-1550116399_

**Comment by sammyjava** [comment]
GCV: @alancleary reports that the URL is incorrect:

> Regarding the GCV location link you provided: the issue is that the URL that came from the service is not correct. The service returned https://gcv.legumeinfo.org/tools/gcv/, but it should be https://gcv.legumeinfo.org/gcv2. As with Funnotate, the chromosome you selected isn't actually in GCV so even with the correct URL you won't get a result.

However, we should not send folks to GCV if the chromosome isn't in it. So even with the correct URL this linkout should be suppressed.

**Comment by sammyjava** [comment]
Funnotate: doesn't display a gene that doesn't exist in a tree: update linkout to say "View this Gene Family in a phylogram" or equivalent.

**Comment by adf-ncgr** [comment]
@sammyjava can you run a test with glyma.Wm82.gnm2.ann1.Glyma.06G065000 and tell me whether the links work for that as expected? (with the likely exception of Jbrowse2)

**Comment by sammyjava** [comment]
We only have  cicar.ICC4958.gnm2.ann1 and phavu.G19833.gnm1.ann1 genes in MiniMine. I can test a phavu gene with the web-components but are you telling me you don't have a standalone testing platform for linkouts? The graphql-server and web-components stuff works as expected, simply spits out what the linkout service provides (and works fine for LegumeMine links).

**Comment by adf-ncgr** [comment]
OK, a phavu gene should probably work as well as the glyma one I suggested. I don't have a (convenient) standalone testing platform for linkouts other than curl. Having a dev instance would of the gene search would make it easier to systematically run through the various species, but isn't essential. The ones that are in there are just a one-size-fits-many approximation at the moment, but I was expecting to have to go through at least one round of refinements on this (likely more than one).

**Comment by sammyjava** [comment]
Well, since Alan is done, I'll go ahead now and mount the gene search jekyll demo. We're done on our end. But we'll not share this with the LIS folks tomorrow, we need to get the linkouts fully working before this leaves the building.

**Comment by adf-ncgr** [comment]
Thanks, I can get linkouts working for at least the minimine genomes by tomorrow.

**Comment by sammyjava** [comment]
OK I'll set the dev jekyll site on MiniMine then so we have a working instance. It'll be obvious that it's limited to anyone that would, say, search for a soybean gene. :)

**Comment by adf-ncgr** [comment]
definitely suboptimal as far as showing off the non-linkout features of the UI! How about you just leave it pointing to legumemine and I do my darnedest to get the linkouts to have only functioning links by tomorrow's meeting? Sorry for dithering.

**Comment by sammyjava** [comment]
Easy to switch. I'll set it on LegumeMine for now, do your darndest. I'll let you know when it's up, I have to load the new front end in and doing some system updates.

**Comment by adf-ncgr** [comment]
thanks! and darn the torpedoes...

**Comment by sammyjava** [comment]
Have at it: https://jekyll-dev.lis.ncgr.org/tools/search/gene-search.html

**Comment by sammyjava** [comment]
Note that we do have a gene family item in the gene search results, so it's a bit weird to say "View this gene's gene family" on the gene linkout when the gene family itself is not linked. But I guess we'll add gene family linkouts in the future, plus the linkouts are for any situation where you have a gene identifier, not just this one. Just thought I'd mention it.

**Comment by StevenCannon-USDA** [comment]
I like it!
Shall we point the Ames crew at it, for testing?

**Comment by adf-ncgr** [comment]
I think I'm on the hook to make the linkouts less prone to send users to unproductive URLs before we unleash the wisdom of the crowds on it. Let's hold off until tomorrow's meeting in any case!

**Comment by sammyjava** [comment]
Well, nothing like LIS testers to turn up more issues, so I'll send out a missive.

**Comment by svengato** [comment]
> Funnotate -- gene is not present in the tree! Should be be showing Funnotate link for genes that aren't in trees, @svengato and @adf-ncgr ??? This results in the "Jump to highlighted feature" link doing nothing, so that's a bug.

Is the problem in Funnotate or in the linkout service? I can make "Jump to highlighted feature" display only the intersection of (requested genes) and (genes in the tree), or alternatively add a "Warning: Not in tree" disclaimer, though these seem only slightly less confusing than what we have now.

**Comment by adf-ncgr** [comment]
I agree.

**Comment by svengato** [comment]
Fixed in Funnotate commit [6a1b5ee](https://github.com/legumeinfo/Funnotate/commit/6a1b5ee7befbe1635d177c833de5de18d5df0efe) - "Jump to highlighted feature" only lists and highlights sequences that exist in the tree.
