### ISSUE TITLE
Gene location linkout testing with cicar.ICC4958.gnm2.ann1.Ca_00001 fails

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/microservices#597]
Gene location linkout testing with cicar.ICC4958.gnm2.ann1.Ca_00001

- [ ] GCV **empty page** with **large error in console** starting with `Ee@https://gcv.legumeinfo.org/gcv2/main.fbb371a5cac15b03.js:1:252853 noMatchError@https://gcv.legumeinfo.org/gcv2/main.fbb371a5cac15b03.js:1:455223" "ERROR Error: Uncaught (in promise): Error: NG04002` @alancleary 
- [ ] JBrowse2 **returns JSON in page** instead of a JBrowse2 @ctcncgr 

Broken linkouts need to be fixed before we show gene search to the LIS folks.

Here are the broken linkouts:

GCV: https://gcv.legumeinfo.org/tools/gcv/search?q=cicar.ICC4958.gnm2.Ca1:6359-6790&sources=lis

JBrowse2: https://cicer.legumeinfo.org/tools/jbrowse2?session=spec-%7B%22views%22%3A%5B%7B%22assembly%22%3A%22cicar.ICC4958.gnm2%22%2C%22loc%22%3A%22cicar.ICC4958.gnm2.Ca1%3A6359-6790%22%2C%22type%22%3A%20%22LGV%22%2C%22tracks%22%3A%5B%22cicar.ICC4958.gnm2.ann1%22%5D%7D%5D%7D

_Originally posted by @sammyjava in https://github.com/legumeinfo/web-components/issues/115#issuecomment-1550125667_

**Comment by adf-ncgr** [comment]
I think this one has been addressed (by returning different links that do work for the gene in question). Feel free to reopen if I'm mistaken
