### ISSUE TITLE
HOWTO build the GCV redis from a GFF from scratch

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/microservices#601]
Suggest that a HOWTO build the GCV redis from a GFF from scratch would be helpful. With sample data that is used.

**Comment by adf-ncgr** [comment]
I was about to push example data and howto command to a branch on gcv-docker-compose but I'm now confused as to whether it belongs there or here. I see @alancleary was thinking about using it for automated testing, but not sure how that's connected to the "getting started" goal of legumeinfo/gcv-docker-compose#6

**Comment by adf-ncgr** [comment]
@alancleary do you have any opinions (strong or mild) on what folder structure we should use for test/example data? Do we want to have separate subfolders per microservice or a top-level folder under the assumption that many of the microservices will share test data? Or should I just put something in place without agonizing too much?

**Comment by sammyjava** [comment]
You can always move it. :)

**Comment by sammyjava** [comment]
My very successful strategy: Do it wrong, then Alan tells me how to do it right. Actually efficient! :)

**Comment by alancleary** [comment]
> @alancleary do you have any opinions (strong or mild) on what folder structure we should use for test/example data? Do we want to have separate subfolders per microservice or a top-level folder under the assumption that many of the microservices will share test data? Or should I just put something in place without agonizing too much?

I think a top level folder makes sense. Then we can use it for unit testing (individual microservices) and integration testing (the microservices running together).

**Comment by adf-ncgr** [comment]
I think we've addressed this sufficiently, so closing.
