### ISSUE TITLE
Return a 404 or 200 with message rather than a 500

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/microservices#603]
Right now a GET or POST to https://services.lis.ncgr.org/gene_linkouts returns a 500, leading one to believe the server is down. It would be better to return a 404, or even a 200 with an error message in the JSON.

**Comment by alancleary** [comment]
What are the details of the request? Are there querystring parameters with the GET or data in the body of the POST? If there is, are the parameters invalid or valid?

**Comment by sammyjava** [comment]
Empty root request. As in checking to see if the service is up.

**Comment by alancleary** [comment]
OK. I think the appropriate response here would be 400 (bad request) since required parameters are missing.

**Comment by sammyjava** [comment]
Oh, yeah, right, a 400 indeed.

**Comment by adf-ncgr** [comment]
fixed in [d11cd02](https://github.com/legumeinfo/microservices/commit/d11cd0256b29aed59c27d36a3e00fd9b90561bf7)
