### ISSUE TITLE
LIS Linkouts from Gene Search

### ISSUE THREAD

**Issue by jd-campbell** [legumeinfo/microservices#620]
On the link outs from Gene Search I was looking for a easy way to quickly get the gene sequence but the link out list only has LegumeMine which has not sequence data.  

I am requesting either add the species specific mine link out to the gene or even better a link to download the gene sequence.

**Comment by adf-ncgr** [comment]
@jd-campbell can you clarify what you mean about LegumeMine not having sequence data? It certainly should, e.g. https://mines.legumeinfo.org/legumemine/sequenceExporter.do?object=483367048
(from clicking the FASTA button on https://mines.legumeinfo.org/legumemine/gene:medtr.A17_HM341.gnm4.ann2.Medtr4g113520)

I can add genus-focused mines to the linkouts too, but just want to make sure we're on the same page. I believe the main way in which the genus-focused mines differ from legumemine at this point is with respect to inclusion of genetic data (QTLs/GWAS).

**Comment by jd-campbell** [comment]
@adf-ncgr  I think we can close this issue.   You have added links to genus-focus mines to the linkouts.
