### ISSUE TITLE
!!! dev.SoyBase LInkOuts do not work!!!

### ISSUE THREAD

**Issue by jd-campbell** [legumeinfo/microservices#621]
Working on the Gene search page on dev.SoyBase -- linkouts are not working

**Comment by adf-ncgr** [comment]
@jd-campbell they seem to be working for me- can you check again?

**Comment by jd-campbell** [comment]
You are right it is working now.  
When I submitted the issue it was not working. I will close this issue.

**Comment by adf-ncgr** [comment]
Thanks @jd-campbell no worries but it would be good to try to ensure these things are more robust so if it recurs if you could send some details about errors from the browser console that would be helpful for diagnosing what's causing the flakiness. Glad it is resolved anyway...

**Comment by alancleary** [comment]
@jd-campbell was it just the linkouts or the entire gene search? We've had issues in the past with InterMine cutting out. It would be nice to know if this may be the same issue or if it's something we haven't seen before.
